// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock/service.go
//

// Package mock_update_userprofile is a generated GoMock package.
package mock_update_userprofile

import (
	reflect "reflect"
	bus "userservice/internal/bus"
	update_userprofile "userservice/internal/features/update_useprofile"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetPresignedUrlForUploading mocks base method.
func (m *MockRepository) GetPresignedUrlForUploading(userProfileImage *update_userprofile.UserProfileImage) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPresignedUrlForUploading", userProfileImage)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPresignedUrlForUploading indicates an expected call of GetPresignedUrlForUploading.
func (mr *MockRepositoryMockRecorder) GetPresignedUrlForUploading(userProfileImage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPresignedUrlForUploading", reflect.TypeOf((*MockRepository)(nil).GetPresignedUrlForUploading), userProfileImage)
}

// UpdateUserProfile mocks base method.
func (m *MockRepository) UpdateUserProfile(data *update_userprofile.UserProfile, bus *bus.EventBus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserProfile", data, bus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserProfile indicates an expected call of UpdateUserProfile.
func (mr *MockRepositoryMockRecorder) UpdateUserProfile(data, bus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserProfile", reflect.TypeOf((*MockRepository)(nil).UpdateUserProfile), data, bus)
}
